### ISSUE TITLE
NPE on Login

### ISSUE THREAD

**Issue by tonybruess** [OvercastNetwork/SportBukkit#10]
Not sure if SportBukkit or CraftBukkit, but putting it here either way.

java.lang.NullPointerException
        at net.minecraft.server.v1_4_R1.PlayerList.attemptLogin(PlayerList.java:259)
        at net.minecraft.server.v1_4_R1.PendingConnection.d(PendingConnection.java:132)
        at net.minecraft.server.v1_4_R1.PendingConnection.c(PendingConnection.java:49)
        at net.minecraft.server.v1_4_R1.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
        at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:29)
        at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
        at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by Electroid** [comment]
Doesn't seem like this occurs anymore.
