### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid locale format

### ISSUE THREAD

**Issue by kblanks** [OvercastNetwork/SportBukkit#187]
Player#getCurrentLocale is throwing this error:

```
java.lang.IllegalArgumentException: Invalid locale format: en-GB
	at org.apache.commons.lang.LocaleUtils.toLocale(LocaleUtils.java:110) ~[sportbukkit-1.9.2-R0.1-SNAPSHOT.jar:git-Bukkit-8bf4588]
	at org.bukkit.craftbukkit.entity.CraftPlayer.getCurrentLocale(CraftPlayer.java:1812) ~[sportbukkit-1.9.2-R0.1-SNAPSHOT.jar:git-Bukkit-8bf4588]
```

The error occurs when using `English (US)` or `English (UK)` locale and I assume all others as well.

**Comment by TheMolkaPL** [comment]
Shluld be `en_US`, not `en-US` which `toLanguageTag()` method returns.

**Comment by kblanks** [comment]
I've found the issue – creating a PR now.
