### ISSUE TITLE
Error when starting SportBukkit

### ISSUE THREAD

**Issue by ianfe9** [OvercastNetwork/SportBukkit#235]
Hello, I compiled SportBukkit, but when I open it, it appears something like this

[09:30:50] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
	at org.bukkit.craftbukkit.inventory.CraftInventory.<init>(CraftInventory.java:44) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at org.bukkit.craftbukkit.entity.CraftMinecartChest.<init>(CraftMinecartChest.java:17) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:202) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.Entity.getBukkitEntity(Entity.java:67) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.EntityMinecartAbstract.<init>(EntityMinecartAbstract.java:114) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.EntityMinecartContainer.<init>(EntityMinecartContainer.java:64) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.EntityMinecartChest.<init>(SourceFile:24) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.WorldGenMineshaftPieces$WorldGenMineshaftCorridor.a(SourceFile:427) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.WorldGenMineshaftPieces$WorldGenMineshaftCorridor.a(SourceFile:475) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.StructureStart.a(SourceFile:42) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.StructureGenerator.a(SourceFile:95) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.ChunkProviderGenerate.recreateStructures(ChunkProviderGenerate.java:333) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at org.bukkit.craftbukkit.generator.NormalChunkGenerator.recreateStructures(NormalChunkGenerator.java:41) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.Chunk.a(Chunk.java:906) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.Chunk.loadNearby(Chunk.java:893) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:172) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:140) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.MinecraftServer.l(MinecraftServer.java:394) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:249) ~[SportBukkit.jar:git-Bukkit-4531cde]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [SportBukkit.jar:git-Bukkit-4531cde]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[09:30:50] [Server thread/ERROR]

**Comment by RainoBoy97** [comment]
This has worked for me every time:
1. Disable the nether in `server.properties`
2. Disable the end in `bukkit.yml`
3. Delete the world folders
4. Make sure PGM has at least one map to load
